// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fa7f8f34-db1a-453e-9dc9-1704d1404bb4";
const char SSID[]        = "Familia Leon";    // Network SSID (name)
const char PASS[]        = "3186277230";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "KthpL@KGJxYjuYO!PanhQm5?H";    // Secret device password

void onLEDStateChange();

float ambulance;
float babyCryingDetection;
float fireAlarm;
float noise;
bool lED_State;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ambulance, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(babyCryingDetection, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(fireAlarm, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(noise, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lED_State, READWRITE, ON_CHANGE, onLEDStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
